apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: velox-front
spec:
  selector:
    service: velox-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
