apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: velox-api
spec:
  selector:
    service: velox-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort