apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: velox-api
spec:
  type: NodePort
  selector:
    service: velox-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
