apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  # target:
  #   name: velox-api-secrets
  data:
{{- range $key, $value := .Values.ssmParameters }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
{{- end }}

# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   namespace: {{ .Values.namespace }}
#   name: api-jwt-keys
# stringData:
# {{- range $key, $value := .Values.ssmParametersJwtKeys }}
#   - key: {{ $value }}
#     name: {{ $key }}
# {{- end }}
