apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: {{ .Values.namespace }}
spec:
  backendType: systemManager
  data:
{{- range $key, $value := .Values.ssmParameters }}
    - key: {{ $value }}
      name: {{ $key }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: api-jwt-keys
stringData:
{{- range $key, $value := .Values.ssmParametersJwtKeys }}
  - key: {{ $value }}
    name: {{ $key }}
{{- end }}
