namespace: velox
frontHost: "velox.sh"
projectName: velox-prod-1
stage: prod-1
loadBalancerName: velox-prod-1-alb
nodejsImageTag: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-prod-1-front:v1.0.a6f14ee 

certificateArn: arn:aws:acm:eu-west-1:156041417813:certificate/90c353ee-c023-4b3b-85f3-d32ed580a3b5
securityGroups: "sg-0818251ac039f7f53" #allow_cloudfront_origin_facing_sg
healthcheckPath: /
subnets: "subnet-0890ba5ed274de236,subnet-00f22ef5ccfd014a7,subnet-0687c9f0c4109a58f" # name: velox-prod-1-public-subnets. CLI: cd 02.VPC; t output -json | jq '.public_subnet_ids.value'    
