apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velox
  name: velox-api
spec:
  selector:
    matchLabels:
      service: velox-api
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: velox-api
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "php-fpm"
      containers:
        - image: {{ .Values.nginxImageTag }}
          name: nginx
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 64m
            limits:
              memory: 128Mi
              cpu: 128m
        - image: {{ .Values.phpImageTag }}
          name: php-fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          resources:
            requests:
              memory: 256Mi
              cpu: 256m
            limits:
              memory: 512Mi
              cpu: 512m
          env:
            - name: DD_SERVICE
              value: "velox-api"
            - name: DD_ENV
              value: "prod"
            - name: DD_TAGS
              value: "platform:velox"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: php-ini-settings
              mountPath: "/usr/local/etc/php/conf.d/settings.ini"
              readOnly: true
            - name: jwt-keys
              mountPath: /var/www/html/config/jwt
              readOnly: true
      volumes:
        - name: php-ini-settings
          configMap:
            name: php-ini-settings
        - name: jwt-keys
          secret:
            secretName: jwt-keys
