
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: velox-front
spec:
  selector:
    matchLabels:
      service: velox-front
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: velox-front
    spec:
      containers:
        - image: {{ .Values.nodejsImageTag }}
          name: nodejs
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 128m
            limits:
              memory: 256Mi
              cpu: 256m
      restartPolicy: Always
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              service: velox-front
