namespace: velox
apiHost: api.velox.sh
projectName: velox-prod-1
stage: prod-1
aws:
  region: eu-west-1

ingress:
  loadBalancerName: velox-prod-1-alb
  healthcheckPath: /api/doc
  certificateArn: arn:aws:acm:eu-west-1:156041417813:certificate/90c353ee-c023-4b3b-85f3-d32ed580a3b5
  securityGroups: "sg-0818251ac039f7f53" # name: allow_cloudfront_origin_facing_sg. CLI: cd 06.EKS; ../terra.sh velox-prod-1 output | grep allow_cloudfront_origin_facing_sg
  subnets: "subnet-0890ba5ed274de236,subnet-00f22ef5ccfd014a7,subnet-0687c9f0c4109a58f" # name: velox-prod-1-public-subnets. CLI: cd 02.VPC; t output -json | jq '.public_subnet_ids.value'    

api:
  phpImageTag: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-prod-1-api:v1.0.build-3.7fcb3f7
  nginxImageTag: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-prod-1-api:v1.0.build-3.7fcb3f7

  replicas: 1
  replicasMessageProcessor: 1
  phpFpmResources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 512m

autoscaler:
  minReplicas: 2
  maxReplicas: 10
  memoryUtilization: 70
  cpuUtilization: 70
  scaleUpPeriodSeconds: 20
  scaleDownPeriodSeconds: 600

config:
  APP_ENV: 'prod'
  CACHE_URL: 'rediss://velox-prod-1-001.velox-prod-1.vpqcar.euw1.cache.amazonaws.com'
  INFOBIP_HOST: 'https://jd4x6n.api.infobip.com'
  INFOBIP_PREFIX: 'App'
  BACKOFFICE_HOST: 'https://backend-api.celesta.io'
  BACKOFFICE_COMPANY_ID: '7'
  BACKOFFICE_CLIENT_ID: 'dd8fe5b8ee24615e60f19ca12a300992'
  BACKOFFICE_USER: 'velox@theluckfactory.net'
  FRONTEND_URL: 'https://velox.sh/'
  BACKEND_URL: 'https://api.velox.sh/api/'
  GOOGLE_BIG_QUERY_PROJECT_ID: 'celesta-325419'
  GOOGLE_BIG_QUERY_BI_PROJECT_ID: 'bi-platform-323915'
  OPTIMOVE_ENABLED: '1'
  OPTIMOVE_API_URL: 'https://api5.optimove.net/'
  BONUS_BRANDS_IDS: '26,33,30,52,54'
  BACKOFFICE_MADNIX_ID: '26'
  BACKOFFICE_WILDSULTAN_ID: '33'
  BACKOFFICE_WINOUI_ID: '30'
  BACKOFFICE_IBIZAPALACE_ID: '52'
  BACKOFFICE_YOKIKANA_ID: '54'
  DD_SAMPLE_RATE: '1'
  DD_SERVICE: 'velox-api'
  EDP_HOST: 'https://api-gw.delivery.email-dp.com'
  SEGMENTATION_TABLE: 'player_value_segmentation'
  CAPTAIN_URL: 'https://captainup.com'
  MYAFF_BQ_DATASET: 'myaff'
  MYAFF_DB_HOST: 'mysql1.myaffiliates.com'
  MYAFF_DB_PORT: '3395'
  MYAFF_DB_NAME: 'sultanaffiliates'
  MYAFF_GOOGLE_CLOUD_PROJECT: 'tlf-bi-project'
  MYAFF_GOOGLE_CLOUD_BUCKET: 'myaff'
phpIniSettings: |
  opcache.enable=1

ssmParameters:
  DATABASE_URL: "/api-secrets/DATABASE_URL"
  JWT_PASSPHRASE: "/api-secrets/JWT_PASSPHRASE"
  MAILER_DSN: "/api-secrets/MAILER_DSN"
  MESSENGER_TRANSPORT_DSN: "/api-secrets/MESSENGER_TRANSPORT_DSN"
  BACKOFFICE_CLIENT_SECRET: "/api-secrets/BACKOFFICE_CLIENT_SECRET"
  BACKOFFICE_PASSWORD: "/api-secrets/BACKOFFICE_PASSWORD"
  GOOGLE_APPLICATION_CREDENTIALS: "/api-secrets/GOOGLE_APPLICATION_CREDENTIALS"
  GOOGLE_BI_APPLICATION_CREDENTIALS: "/api-secrets/GOOGLE_BI_APPLICATION_CREDENTIALS"
  INFOBIP_KEY: "/api-secrets/INFOBIP_KEY"
  EDP_CLIENT_SECRET: "/api-secrets/EDP_CLIENT_SECRET"
  EDP_CLIENT_ID: "/api-secrets/EDP_CLIENT_ID"
  EDP_MADNIX_ID: "/api-secrets/EDP_MADNIX_ID"
  EDP_MADNIX_SECRET: "/api-secrets/EDP_MADNIX_SECRET"
  EDP_WINOUI_ID: "/api-secrets/EDP_WINOUI_ID"
  EDP_WINOUI_SECRET: "/api-secrets/EDP_WINOUI_SECRET"
  EDP_WILDSULTAN_ID: "/api-secrets/EDP_WILDSULTAN_ID"
  EDP_WILDSULTAN_SECRET: "/api-secrets/EDP_WILDSULTAN_SECRET"
  AWS_KEY: "/api-secrets/AWS_KEY"
  AWS_SECRET: "/api-secrets/AWS_SECRET"
  PAYMENT_ALERT_DB_DSN: "/api-secrets/PAYMENT_ALERT_DB_DSN"
  PAYMENT_ALERT_WEBHOOK: "/api-secrets/PAYMENT_ALERT_WEBHOOK"
  SLACK_WEBHOOK: "/api-secrets/SLACK_WEBHOOK"
  BLACKFIRE_SERVER_ID: "/api-secrets/BLACKFIRE_SERVER_ID"
  BLACKFIRE_CLIENT_ID: "/api-secrets/BLACKFIRE_CLIENT_ID"
  OPTIMOVE_API_KEY: "/api-secrets/OPTIMOVE_API_KEY"
  CAPTAIN_UP_SECRET_MADNIX: "/api-secrets/CAPTAIN_UP_SECRET_MADNIX"
  CAPTAIN_UP_API_KEY_MADNIX: "/api-secrets/CAPTAIN_UP_API_KEY_MADNIX"
  CAPTAIN_UP_SECRET_IBIZAPALACE: "/api-secrets/CAPTAIN_UP_SECRET_IBIZAPALACE"
  CAPTAIN_UP_API_KEY_IBIZAPALACE: "/api-secrets/CAPTAIN_UP_API_KEY_IBIZAPALACE"
  CAPTAIN_UP_SECRET_YOKIKANA: "/api-secrets/CAPTAIN_UP_SECRET_YOKIKANA"
  CAPTAIN_UP_API_KEY_YOKIKANA: "/api-secrets/CAPTAIN_UP_API_KEY_YOKIKANA"
  AWS_REGION: "/api-secrets/AWS_REGION"
  AWS_ACCESS_KEY_ID: "/api-secrets/AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "/api-secrets/AWS_SECRET_ACCESS_KEY"
  AWS_BUCKET_MADNIX: "/api-secrets/AWS_BUCKET_MADNIX"
  AWS_BUCKET_WILDSULTAN: "/api-secrets/AWS_BUCKET_WILDSULTAN"
  AWS_BUCKET_WINOUI: "/api-secrets/AWS_BUCKET_WINOUI"
  AWS_BUCKET_IBIZAPALACE: "/api-secrets/AWS_BUCKET_IBIZAPALACE"
  AWS_BUCKET_YOKIKANA: "/api-secrets/AWS_BUCKET_YOKIKANA"
  MYAFF_DB_USER: "/api-secrets/MYAFF_DB_USER"
  MYAFF_DB_PASSWORD: "/api-secrets/MYAFF_DB_PASSWORD"
  MYAFF_GOOGLE_CLOUD_CREDENTIALS: "/api-secrets/MYAFF_GOOGLE_CLOUD_CREDENTIALS"
  MYAFF_DB_SSL_CA: "/api-secrets/MYAFF_DB_SSL_CA"

ssmParametersJwtKeys:
  publicKey: "/api-secrets/PUBLIC_KEY"
  privateKey: "/api-secrets/PRIVATE_KEY"

cronjobs:
  - name: velox-job-global-payment-alert-check
    schedule: "*/5 * * * *"
    command: ["./bin/console", "app:payment-alerts"]
  - name: velox-job-edp-data-sync-to-bq-madnix
    schedule: "30 22 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Madnix"]
  - name: velox-job-edp-data-sync-to-bq-winoui
    schedule: "30 0 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Winoui"]
  - name: velox-job-edp-data-sync-to-bq-wildsultan
    schedule: "30 2 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Wildsultan"]
  - name: velox-job-segment-bonus-sanitizer
    schedule: "30 00 * * *"
    command: ["./bin/console", "app:segment:bonus:sanitizer"]
  - name: velox-job-bonus-enable
    schedule: "*/10 * * * *"
    command: ["./bin/console", "app:bonus-enable"]
  - name: velox-job-metrics-update
    schedule: "30 01 * * *"
    command: ["./bin/console", "app:metrics-update"]
  - name: velox-job-edp-cleanup
    schedule: "30 03 * * *"
    command: ["./bin/console", "app:edp:campaign-cleanup"]
  - name: velox-promo-cleanup
    schedule: "10 0 * * *"
    command: ["./bin/console", "app:promo:cleanup"]
  - name: velox-job-player-tier-update-ws
    schedule: "20 0 * * *"
    command: ["./bin/console", "app:player-tier-update", "33"]
  - name: velox-job-player-tier-update-ip
    schedule: "40 0 * * *"
    command: ["./bin/console", "app:player-tier-update", "52"]
  - name: velox-job-player-tier-update-wo
    schedule: "10 1 * * *"
    command: ["./bin/console", "app:player-tier-update", "30"]
  - name: velox-assign-bonuses-mx
    schedule: "0 1 * * *"
    command: ["./bin/console", "app:assign_bonuses", "26"]
  - name: velox-job-sync-myaff-bq
    schedule: "30 07* * *"
    command: ["./bin/console", "myaff:sync-database"]
