apiHost: velox-api.tlf.dev
projectName: velox-prod-1

ingress:
  loadBalancerName: velox-prod-1-alb
  healthcheckPath: /api/doc
  certificateArn: arn:aws:acm:eu-west-1:156041417813:certificate/a6e631a1-3073-4ebb-91d0-b973602876a1
  securityGroups: "sg-0818251ac039f7f53" # name: allow_cloudfront_origin_facing_sg. CLI: cd 06.EKS; ../terra.sh velox-prod-1 output | grep allow_cloudfront_origin_facing_sg
  subnets: "subnet-0890ba5ed274de236,subnet-00f22ef5ccfd014a7,subnet-0687c9f0c4109a58f" # name: velox-prod-1-public-subnets. CLI: cd 02.VPC; t output -json | jq '.public_subnet_ids.value'    

api:
  phpImageTag: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
  nginxImageTag: nginx:latest
  ddStage: prod
  replicas: 6
  replicasMessageProcessor: 2
  phpFpmResources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 512Mi
      cpu: 512m

autoscaler:
  minReplicas: 2
  maxReplicas: 10
  memoryUtilization: 70
  cpuUtilization: 70
  scaleUpPeriodSeconds: 20
  scaleDownPeriodSeconds: 600

config:
  APP_ENV: 'prod'
  CACHE_URL: 'rediss://velox-prod-1-001.velox-prod-1.vpqcar.euw1.cache.amazonaws.com'
  INFOBIP_HOST: 'https://jd4x6n.api.infobip.com'
  INFOBIP_PREFIX: 'App'
  BACKOFFICE_HOST: 'https://backend-api.celesta.io'
  BACKOFFICE_COMPANY_ID: '7'
  BACKOFFICE_CLIENT_ID: 'dd8fe5b8ee24615e60f19ca12a300992'
  BACKOFFICE_USER: 'velox@theluckfactory.net'
  FRONTEND_URL: 'https://velox.tlf.dev/'
  BACKEND_URL: 'https://velox-api.tlf.dev/api/'
  GOOGLE_BIG_QUERY_PROJECT_ID: 'celesta-325419'
  GOOGLE_BIG_QUERY_BI_PROJECT_ID: 'bi-platform-323915'
  OPTIMOVE_ENABLED: '1'
  OPTIMOVE_API_URL: 'https://api5.optimove.net/'
  BONUS_BRANDS_IDS: '26,33,30,52,54'
  BACKOFFICE_MADNIX_ID: '26'
  BACKOFFICE_WILDSULTAN_ID: '33'
  BACKOFFICE_WINOUI_ID: '30'
  BACKOFFICE_IBIZAPALACE_ID: '52'
  BACKOFFICE_YOKIKANA_ID: '54'
  DD_SAMPLE_RATE: '1'
  DD_SERVICE: 'velox-api'
  EDP_HOST: 'https://api-gw.delivery.email-dp.com'
  SEGMENTATION_TABLE: 'player_value_segmentation'
  CAPTAIN_URL: 'https://captainup.com'
  MYAFF_BQ_DATASET: 'myaff'
  MYAFF_DB_HOST: 'mysql1.myaffiliates.com'
  MYAFF_DB_PORT: '3395'
  MYAFF_DB_NAME: 'sultanaffiliates'
  MYAFF_GOOGLE_CLOUD_PROJECT: 'tlf-bi-project'
  MYAFF_GOOGLE_CLOUD_BUCKET: 'myaff'
phpIniSettings: |
  opcache.enable=1

ssmParameters:
  DATABASE_URL: "/velox/database_url"
  JWT_PASSPHRASE: "/velox/jwt_passphrase"
  MAILER_DSN: "/velox/mailer_dsn"
  MESSENGER_TRANSPORT_DSN: "/velox/messenger_transport_dsn"
  BACKOFFICE_CLIENT_SECRET: "/velox/backoffice_client_secret"
  BACKOFFICE_PASSWORD: "/velox/backoffice_password"
  GOOGLE_APPLICATION_CREDENTIALS: "/velox/google_application_credentials"
  GOOGLE_BI_APPLICATION_CREDENTIALS: "/velox/google_bi_application_credentials"
  INFOBIP_KEY: "/velox/infobip_key"
  EDP_CLIENT_SECRET: "/velox/edp_client_secret"
  EDP_CLIENT_ID: "/velox/edp_client_id"
  EDP_MADNIX_ID: "/velox/edp_madnix_id"
  EDP_MADNIX_SECRET: "/velox/edp_madnix_secret"
  EDP_WINOUI_ID: "/velox/edp_winoui_id"
  EDP_WINOUI_SECRET: "/velox/edp_winoui_secret"
  EDP_WILDSULTAN_ID: "/velox/edp_wildsultan_id"
  EDP_WILDSULTAN_SECRET: "/velox/edp_wildsultan_secret"
  AWS_KEY: "/velox/aws_key"
  AWS_SECRET: "/velox/aws_secret"
  PAYMENT_ALERT_DB_DSN: "/velox/payment_alert_db_dsn"
  PAYMENT_ALERT_WEBHOOK: "/velox/payment_alert_webhook"
  SLACK_WEBHOOK: "/velox/slack_webhook"
  BLACKFIRE_SERVER_ID: "/velox/blackfire_server_id"
  BLACKFIRE_CLIENT_ID: "/velox/blackfire_client_id"
  OPTIMOVE_API_KEY: "/velox/optimove_api_key"
  CAPTAIN_UP_SECRET_MADNIX: "/velox/captain_up_secret_madnix"
  CAPTAIN_UP_API_KEY_MADNIX: "/velox/captain_up_api_key_madnix"
  CAPTAIN_UP_SECRET_IBIZAPALACE: "/velox/captain_up_secret_ibizapalace"
  CAPTAIN_UP_API_KEY_IBIZAPALACE: "/velox/captain_up_api_key_ibizapalace"
  CAPTAIN_UP_SECRET_YOKIKANA: "/velox/captain_up_secret_yokikana"
  CAPTAIN_UP_API_KEY_YOKIKANA: "/velox/captain_up_api_key_yokikana"
  AWS_REGION: "/velox/aws_region"
  AWS_ACCESS_KEY_ID: "/velox/aws_access_key_id"
  AWS_SECRET_ACCESS_KEY: "/velox/aws_secret_access_key"
  AWS_BUCKET_MADNIX: "/velox/aws_bucket_madnix"
  AWS_BUCKET_WILDSULTAN: "/velox/aws_bucket_wildsultan"
  AWS_BUCKET_WINOUI: "/velox/aws_bucket_winoui"
  AWS_BUCKET_IBIZAPALACE: "/velox/aws_bucket_ibizapalace"
  AWS_BUCKET_YOKIKANA: "/velox/aws_bucket_yokikana"
  MYAFF_DB_USER: "/velox/myaff_db_user"
  MYAFF_DB_PASSWORD: "/velox/myaff_db_password"
  MYAFF_GOOGLE_CLOUD_CREDENTIALS: "/velox/myaff_google_cloud_credentials"
  MYAFF_DB_SSL_CA: "/velox/myaff_db_ssl_ca"

ssmParametersJwtKeys:
  publicKey: "/velox/public_key"
  privateKey: "/velox/private_key"

cronjobs:
  - name: velox-job-global-payment-alert-check
    schedule: "*/5 * * * *"
    command: ["./bin/console", "app:payment-alerts"]
  - name: velox-job-edp-data-sync-to-bq-madnix
    schedule: "30 22 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Madnix"]
  - name: velox-job-edp-data-sync-to-bq-winoui
    schedule: "30 0 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Winoui"]
  - name: velox-job-edp-data-sync-to-bq-wildsultan
    schedule: "30 2 * * *"
    command: ["./bin/console", "app:edp:campaign-bq-export", "--brandName=Wildsultan"]
  - name: velox-job-segment-bonus-sanitizer
    schedule: "30 00 * * *"
    command: ["./bin/console", "app:segment:bonus:sanitizer"]
  - name: velox-job-bonus-enable
    schedule: "*/10 * * * *"
    command: ["./bin/console", "app:bonus-enable"]
  - name: velox-job-metrics-update
    schedule: "30 01 * * *"
    command: ["./bin/console", "app:metrics-update"]
  - name: velox-job-edp-cleanup
    schedule: "30 03 * * *"
    command: ["./bin/console", "app:edp:campaign-cleanup"]
  - name: velox-promo-cleanup
    schedule: "10 0 * * *"
    command: ["./bin/console", "app:promo:cleanup"]
  - name: velox-job-player-tier-update-ws
    schedule: "20 0 * * *"
    command: ["./bin/console", "app:player-tier-update", "33"]
  - name: velox-job-player-tier-update-ip
    schedule: "40 0 * * *"
    command: ["./bin/console", "app:player-tier-update", "52"]
  - name: velox-job-player-tier-update-wo
    schedule: "10 1 * * *"
    command: ["./bin/console", "app:player-tier-update", "30"]
  - name: velox-assign-bonuses-mx
    schedule: "0 1 * * *"
    command: ["./bin/console", "app:assign_bonuses", "26"]
