---
# Source: velox-api/templates/api-deployment.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: velox-api
  namespace: velox
spec:
  minAvailable: 1
  selector:
    matchLabels:
      service: velox-api
---
# Source: velox-api/templates/api-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: velox
  name: api-config
data:
  APP_ENV: 'prod'
  CACHE_URL: ''
  INFOBIP_HOST: 'https://jd4x6n.api.infobip.com'
  INFOBIP_PREFIX: 'App'
  BACKOFFICE_HOST: 'https://backend-api.celesta.io'
  BACKOFFICE_COMPANY_ID: '7'
  BACKOFFICE_CLIENT_ID: 'dd8fe5b8ee24615e60f19ca12a300992'
  BACKOFFICE_USER: 'velox@theluckfactory.net'
  FRONTEND_URL: 'https://velox.tlf.dev/'
  BACKEND_URL: 'https://velox-api.tlf.dev/api/'
  GOOGLE_BIG_QUERY_PROJECT_ID: 'celesta-325419'
  GOOGLE_BIG_QUERY_BI_PROJECT_ID: 'bi-platform-323915'
  OPTIMOVE_ENABLED: '1'
  OPTIMOVE_API_URL: 'https://api5.optimove.net/'
  BONUS_BRANDS_IDS: '26,33,30,52,54'
  BACKOFFICE_MADNIX_ID: '26'
  BACKOFFICE_WILDSULTAN_ID: '33'
  BACKOFFICE_WINOUI_ID: '30'
  BACKOFFICE_IBIZAPALACE_ID: '52'
  BACKOFFICE_YOKIKANA_ID: '54'
  DD_SAMPLE_RATE: '1'
  DD_SERVICE: 'velox-api'
  EDP_HOST: 'https://api-gw.delivery.email-dp.com'
  SEGMENTATION_TABLE: 'player_value_segmentation'
  CAPTAIN_URL: 'https://captainup.com'
  MYAFF_BQ_DATASET: 'myaff'
  MYAFF_DB_HOST: 'mysql1.myaffiliates.com'
  MYAFF_DB_PORT: '3395'
  MYAFF_DB_NAME: 'sultanaffiliates'
  MYAFF_GOOGLE_CLOUD_PROJECT: 'tlf-bi-project'
  MYAFF_GOOGLE_CLOUD_BUCKET: 'myaff'
---
# Source: velox-api/templates/api-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: velox
  name: api-php-config
data:
  php-ini-settings: |
    opcache.enable=1
---
# Source: velox-api/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: velox
  name: velox-api
spec:
  selector:
    service: velox-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Source: velox-api/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velox
  name: velox-api
spec:
  selector:
    matchLabels:
      service: velox-api
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: velox-api
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "php-fpm"
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 64m
            limits:
              memory: 128Mi
              cpu: 128m
        - image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
          name: php-fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          resources:
            requests:
              memory: 256Mi
              cpu: 256m
            limits:
              memory: 512Mi
              cpu: 512m
---
# Source: velox-api/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velox
  name: velox-api-message-processor
spec:
  selector:
    matchLabels:
      service: velox-api-message-processor
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: velox-api-message-processor
    spec:
      containers:
        - image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
          name: php-fpm
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          resources:
            requests:
              memory: 256Mi
              cpu: 256m
            limits:
              memory: 512Mi
              cpu: 512m
---
# Source: velox-api/templates/api-autoscaler.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: velox-api
  namespace: velox
  labels:
    service: velox-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velox-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 600
---
# Source: velox-api/templates/api-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velox-api
  namespace: velox
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=61,routing.http.xff_header_processing.mode=preserve
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/healthcheck-path: /api/doc
    alb.ingress.kubernetes.io/healthy-threshold-count: '3'
    alb.ingress.kubernetes.io/tags: project=velox,Name=velox-prod-1-alb,Namespace=velox,Stage=
    alb.ingress.kubernetes.io/group.name: velox-prod-1
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: 'true'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:156041417813:certificate/a6e631a1-3073-4ebb-91d0-b973602876a1
    alb.ingress.kubernetes.io/load-balancer-name: velox-prod-1-alb
    alb.ingress.kubernetes.io/security-groups: sg-0818251ac039f7f53
    alb.ingress.kubernetes.io/subnets: subnet-0890ba5ed274de236,subnet-00f22ef5ccfd014a7,subnet-0687c9f0c4109a58f

# kubernetes.io/ingress.class: "alb"
spec:
  ingressClassName: alb
  rules:
  - host: "velox-api.tlf.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velox-api
            port:
              number: 80
---
# Source: velox-api/templates/api-cronjobs.yaml
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-global-payment-alert-check
#   namespace: velox
# spec:
#   schedule: "*/5 * * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-global-payment-alert-check
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:payment-alerts"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-edp-data-sync-to-bq-madnix
#   namespace: velox
# spec:
#   schedule: "30 22 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-edp-data-sync-to-bq-madnix
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:edp:campaign-bq-export","--brandName=Madnix"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-edp-data-sync-to-bq-winoui
#   namespace: velox
# spec:
#   schedule: "30 0 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-edp-data-sync-to-bq-winoui
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:edp:campaign-bq-export","--brandName=Winoui"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-edp-data-sync-to-bq-wildsultan
#   namespace: velox
# spec:
#   schedule: "30 2 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-edp-data-sync-to-bq-wildsultan
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:edp:campaign-bq-export","--brandName=Wildsultan"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-segment-bonus-sanitizer
#   namespace: velox
# spec:
#   schedule: "30 00 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-segment-bonus-sanitizer
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:segment:bonus:sanitizer"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-bonus-enable
#   namespace: velox
# spec:
#   schedule: "*/10 * * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-bonus-enable
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:bonus-enable"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-metrics-update
#   namespace: velox
# spec:
#   schedule: "30 01 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-metrics-update
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:metrics-update"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-edp-cleanup
#   namespace: velox
# spec:
#   schedule: "30 03 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-edp-cleanup
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:edp:campaign-cleanup"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-promo-cleanup
#   namespace: velox
# spec:
#   schedule: "10 0 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-promo-cleanup
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:promo:cleanup"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-player-tier-update-ws
#   namespace: velox
# spec:
#   schedule: "20 0 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-player-tier-update-ws
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:player-tier-update","33"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-player-tier-update-ip
#   namespace: velox
# spec:
#   schedule: "40 0 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-player-tier-update-ip
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:player-tier-update","52"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-job-player-tier-update-wo
#   namespace: velox
# spec:
#   schedule: "10 1 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-job-player-tier-update-wo
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:player-tier-update","30"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: velox-assign-bonuses-mx
#   namespace: velox
# spec:
#   schedule: "0 1 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 7
#   failedJobsHistoryLimit: 7
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: velox-assign-bonuses-mx
#               image: 156041417813.dkr.ecr.eu-west-1.amazonaws.com/velox-api:latest
#               imagePullPolicy: Always
#               command: ["./bin/console","app:assign_bonuses","26"]
#               envFrom:
#                 - configMapRef:
#                     name: api-config
#                 - secretRef:
#                     name: api-secrets
#           restartPolicy: OnFailure
#
